baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "To Be Decided"

[Params]
  Author = "Kaito Yamada"
  Birth = "Wed, Dec 14, 1983"
  GoogleAnalyticsUserID = "kaitoy1214"
  GravatarHash = "5fbe47b2a4b3637dd26dfc9a49381895"
  Facebook = "yamada.kaito.90"
  Github = "Kaitoy"
  Disqus = "kaitoy"
