baseurl = "http://tbd.kaitoy.xyz"
languageCode = "en-us"
title = "To Be Decided"
theme = "hugo_theme_robust"

[Params]
  Author = "Kaito Yamada"
  Birth = "Wed, Dec 14, 1983"
  DateForm = "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID = "UA-65248565-1"
  GravatarHash = "5fbe47b2a4b3637dd26dfc9a49381895"
  Facebook = "yamada.kaito.90"
  Github = "Kaitoy"
  disqusShortname = "kaitoy-tobedecided"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  ShowRelatedPost = "True"
  ShowTagCloud = "True"

[Indexes]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:title/"

MetadataFormat = "toml"
